// image imports commented out because images now live in the public/cards folder

const cardList = [
  {
    name: "chariot",
    picture: "/cards/chariot.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  { name: "death", picture: "/cards/death.jpg", arcana: "major", upward: "", downward: "" },
  { name: "devil", picture: "/cards/devil.jpg", arcana: "major", upward: "", downward: "" },
  {
    name: "emperor",
    picture: "/cards/emperor.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  {
    name: "empress",
    picture: "/cards/empress.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  { name: "fool", picture: "/cards/fool.jpg", arcana: "major", upward: "", downward: "" },
  {
    name: "hanged man",
    picture: "/cards/hanged_man.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  {
    name: "hermit",
    picture: "/cards/hermit.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  {
    name: "hierophant",
    picture: "/cards/hierophant.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  {
    name: "judgement",
    picture: "/cards/judgement.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  {
    name: "justice",
    picture: "/cards/justice.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  {
    name: "lovers",
    picture: "/cards/lovers.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  {
    name: "magician",
    picture: "/cards/magician.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  { name: "moon", picture: "/cards/moon.jpg", arcana: "major", upward: "", downward: "" },
  {
    name: "priestess",
    picture: "/cards/priestess.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  { name: "star", picture: "/cards/star.jpg", arcana: "major", upward: "", downward: "" },
  {
    name: "strength",
    picture: "/cards/strength.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  { name: "sun", picture: "/cards/sun.jpg", arcana: "major", upward: "", downward: "" },
  {
    name: "temperance",
    picture: "/cards/temperance.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  { name: "tower", picture: "/cards/tower.jpg", arcana: "major", upward: "", downward: "" },
  {
    name: "wheel of fortune",
    picture: "/cards/wheel_of_fortune.jpg",
    arcana: "major",
    upward: "",
    downward: "",
  },
  { name: "world", picture: "/cards/world.jpg", arcana: "major", upward: "", downward: "" },
  {
    name: "Ace of Cups",
    picture: "/cards/C-01.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Two of Cups",
    picture: "/cards/C-02.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Three of Cups",
    picture: "/cards/C-03.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Four of Cups",
    picture: "/cards/C-04.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Five of Cups",
    picture: "/cards/C-05.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Six of Cups",
    picture: "/cards/C-06.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Seven of Cups",
    picture: "/cards/C-07.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Eight of Cups",
    picture: "/cards/C-08.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Nine of Cups",
    picture: "/cards/C-09.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Ten of Cups",
    picture: "/cards/C-10.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Page of Cups",
    picture: "/cards/P-C.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Knight of Cups",
    picture: "/cards/KN-C.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Queen of Cups",
    picture: "/cards/Q-C.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "King of Cups",
    picture: "/cards/K-C.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Ace of Pentacles",
    picture: "/cards/P-01.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Two of Pentacles",
    picture: "/cards/P-02.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Three of Pentacles",
    picture: "/cards/P-03.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Four of Pentacles",
    picture: "/cards/P-04.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Five of Pentacles",
    picture: "/cards/P-05.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Six of Pentacles",
    picture: "/cards/P-06.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Seven of Pentacles",
    picture: "/cards/P-07.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Eight of Pentacles",
    picture: "/cards/P-08.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Nine of Pentacles",
    picture: "/cards/P-09.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Ten of Pentacles",
    picture: "/cards/P-10.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Page of Pentacles",
    picture: "/cards/P-P.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Knight of Pentacles",
    picture: "/cards/KN-P.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Queen of Pentacles",
    picture: "/cards/Q-P.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "King of Pentacles",
    picture: "/cards/K-P.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Ace of Swords",
    picture: "/cards/S-01.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Two of Swords",
    picture: "/cards/S-02.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Three of Swords",
    picture: "/cards/S-03.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Four of Swords",
    picture: "/cards/S-04.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Five of Swords",
    picture: "/cards/S-05.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Six of Swords",
    picture: "/cards/S-06.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Seven of Swords",
    picture: "/cards/S-07.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Eight of Swords",
    picture: "/cards/S-08.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Nine of Swords",
    picture: "/cards/S-09.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Ten of Swords",
    picture: "/cards/S-10.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Page of Swords",
    picture: "/cards/P-S.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Knight of Swords",
    picture: "/cards/KN-S.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Queen of Swords",
    picture: "/cards/Q-S.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "King of Swords",
    picture: "/cards/K-S.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Ace of Wands",
    picture: "/cards/W-01.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Two of Wands",
    picture: "/cards/W-02.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Three of Wands",
    picture: "/cards/W-03.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Four of Wands",
    picture: "/cards/W-04.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Five of Wands",
    picture: "/cards/W-05.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Six of Wands",
    picture: "/cards/W-06.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Seven of Wands",
    picture: "/cards/W-07.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Eight of Wands",
    picture: "/cards/W-08.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Nine of Wands",
    picture: "/cards/W-09.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Ten of Wands",
    picture: "/cards/W-10.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Page of Wands",
    picture: "/cards/P-W.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Knight of Wands",
    picture: "/cards/KN-W.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "Queen of Wands",
    picture: "/cards/Q-W.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
  {
    name: "King of Wands",
    picture: "/cards/K-W.jpg",
    arcana: "minor",
    upward: "",
    downward: "",
  },
];

export default cardList;
